version: '3.8'

services:
  multipepgen-ui:
    build: .
    container_name: multipepgen-ui-v2
    restart: always
    ports:
      - "80:80"
    networks:
      - peptools_network

networks:
  peptools_network:
    external: true
