version: '3.8'

services:
  multipepgen-ui:
    build: .
    container_name: multipepgen-ui-v2
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=multipepgen.medellin.unal.edu.co
      - LETSENCRYPT_HOST=multipepgen.medellin.unal.edu.co
      - LETSENCRYPT_EMAIL=laboratorio@medellin.unal.edu.co
    networks:
      - inverpep_default

networks:
  inverpep_default:
    external: true
